ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';

ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';

ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ NULL;
